In [40]:
import pickle

# Using simple tokenizer

In [41]:
with open('raw_sentences.pickle', 'rb') as file:
    all_sentences = pickle.load(file)


In [42]:
len(all_sentences)

99766

```Total number of sentences: 99766```

In [43]:
single_sequence = [word for sent in all_sentences for word in sent]
len(single_sequence)

858434

In [44]:
unique_words = list(set(single_sequence))
len(unique_words)

230891

#### Raw Dataset
```
Total number of words: 858434
Total number of unique words: 230891
Percentage of unique words among all words: 26.9%
```

Lesser percentage = more repition

### Annotated Dataset

In [45]:
with open(r'..\AnnotatedDatasetParsing\full_dataset_131.pickle', 'rb') as file:
    obj = pickle.load(file)

ad_sentences = []
for sentence in obj:
    temp = []
    for chunk in sentence.list_of_chunks:
        for word in chunk.list_of_words:
            temp.append(word.kannada_word)
    ad_sentences.append(temp)

len(ad_sentences)

6318

In [48]:
single_sequence_annotated = [word for sent in ad_sentences for word in sent]
len(single_sequence_annotated)

103475

In [50]:
unique_annotated_words = list(set(single_sequence_annotated))
len(unique_annotated_words)

14690

#### Annotated Dataset
```
Total number of words: 103475
Total number of unique words: 14690
Percentage of unique words among all words: 14.2%
```

### Number of similar words between annotated dataset and raw dataset

In [52]:
len(list(set(unique_annotated_words) - set(unique_words)))

8210

In [54]:
len(list(set(unique_words) & set(unique_annotated_words)))

6480

# Using special character tokenizer

In [55]:
with open('delimited_sentences.pickle', 'rb') as file:
    delimited_sentences = pickle.load(file)
len(delimited_sentences)

99766

In [56]:
delimited_single_sequence = [word for sent in delimited_sentences for word in sent]
len(delimited_single_sequence)

1082609

In [57]:
delimited_unique_words = list(set(delimited_single_sequence))
len(delimited_unique_words)

186852

```
(Total) Extra words obtained by delimiting special characters also:  858434 --> 1082609
Unique words obtained by delimiting special characters also: 230891 --> 186852
```

In [59]:
len(list(set(delimited_unique_words) & set(unique_annotated_words)))

6914

# Comparing with fastText unique words

In [66]:
fastText_words = []

with open('../Embeddings/all_words.txt', 'r', encoding='utf-8') as f:
    for line in f:
        line = line.strip()
        
        fastText_words.append(line)
len(fastText_words)

1600000

In [64]:
len(list(set(delimited_unique_words) & set(fastText_words)))

91590

```
Size of fastText Embeddings: 91590
Size of unique words in raw dataset: 91590
91_590 out of 1_86_852 have embeddings in fastText. (49.02%)
Need to check for stemming and stuff (but getting correct word embeddings from the stem requires the word's POS tag)
```

```
What to do about the remaining unknown embeddigngs?
```